# Generated by Django 2.1.3 on 2019-06-23 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=45)),
                ('recorder', models.CharField(max_length=45)),
                ('updater', models.CharField(max_length=45)),
                ('lastUpdate', models.DateField()),
                ('createDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upPerson', models.CharField(max_length=45)),
                ('createPerson', models.CharField(max_length=45)),
                ('createDate', models.DateField()),
                ('updatePerson', models.CharField(max_length=45)),
                ('updateDate', models.DateField()),
                ('status', models.CharField(max_length=45)),
                ('content', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('ar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.ApplicationRecord')),
                ('managerCompanyName', models.CharField(max_length=45)),
                ('managerCompanyAddr', models.CharField(max_length=45)),
                ('managerCompanyChargerName', models.CharField(max_length=45)),
                ('managerCompanyPhone', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('ar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.ApplicationRecord')),
                ('thingName', models.CharField(max_length=45)),
                ('thingNumber', models.CharField(max_length=45)),
                ('structI', models.CharField(max_length=45)),
                ('structII', models.CharField(max_length=45)),
                ('thingArea', models.IntegerField()),
                ('stayPeopleNumber', models.IntegerField()),
                ('thingAddr', models.CharField(max_length=45)),
                ('thingAddrPostcode', models.CharField(max_length=45)),
                ('thingRentCost', models.CharField(max_length=45)),
                ('thingManageCost', models.CharField(max_length=45)),
                ('thingGiftCost', models.CharField(max_length=45)),
                ('thingDepositCost', models.CharField(max_length=45)),
                ('thingReliefCost', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Live',
            fields=[
                ('ar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.ApplicationRecord')),
                ('settlementDate', models.DateField()),
                ('contractDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('ar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.ApplicationRecord')),
                ('userNameWrite', models.CharField(max_length=45)),
                ('userNameAlias', models.CharField(max_length=45)),
                ('userNameRead', models.CharField(max_length=45)),
                ('userAddr', models.CharField(max_length=45)),
                ('userAddrPostcode', models.CharField(max_length=45)),
                ('userPhone', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('ar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.ApplicationRecord')),
                ('AD', models.CharField(max_length=45)),
                ('agencyFee', models.CharField(max_length=45)),
                ('backFee', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('ar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.ApplicationRecord')),
                ('tip', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='ar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ApplicationRecord'),
        ),
        migrations.AddField(
            model_name='comment',
            name='ar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ApplicationRecord'),
        ),
    ]
