# Generated by Django 2.1.8 on 2019-07-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='leader',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
