# Generated by Django 2.1.3 on 2019-06-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190624_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationrecord',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='applicationrecord',
            name='lastUpdate',
            field=models.DateTimeField(),
        ),
    ]
