# Generated by Django 2.1.3 on 2019-06-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20190626_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationrecord',
            name='lastUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
