# Generated by Django 2.1.3 on 2019-06-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190626_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationrecord',
            name='lastUpdate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updateDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
