# Generated by Django 2.1.8 on 2019-07-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20190626_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationrecord',
            name='manager_number',
            field=models.CharField(default='unset', max_length=45),
        ),
        migrations.AddField(
            model_name='applicationrecord',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
