# Generated by Django 2.1.3 on 2019-07-02 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_applicationrecord_specify_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationrecord',
            name='specify_flag',
        ),
    ]
