# Generated by Django 2.1.8 on 2019-07-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_applicationrecord_specify_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(default='unchecked', max_length=45),
        ),
    ]
